apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pypod-helloworld
  name: pypod-helloworld
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pypod-helloworld
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pypod-helloworld
    spec:
      containers:
      - image: jlessey/pypod-helloworld:v1.0.0 
        imagePullPolicy: IfNotPresent
        name: pypod-helloworld
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pypod-helloworld
    app.kubernetes.io/instance: pypod-helloworld
  name: pypod-helloworld
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pypod-helloworld
  type: NodePort
status:
  loadBalancer: {}
